#!/bin/sh
VM_NAME=boot2docker-vm
VBM=VBoxManage

DOCKER_PORT=4243
SSH_HOST_PORT=2022

VM_DISK=./boot2docker.vmdk
VM_DISK_SIZE=40000

VM_MEM=1024

BOOT2DOCKER_ISO=./boot2docker.iso

test -f $HOME/.boot2docker/profile && . $HOME/.boot2docker/profile

get_latest_release_name() {
    curl 'https://api.github.com/repos/steeve/boot2docker/releases' 2>/dev/null | grep "tag_name" | awk '{print $2}' | sed 's/[",]*//g' | head -1
}

download_latest() {
    LATEST_RELEASE=`get_latest_release_name`
    log "Latest version is $LATEST_RELEASE, downloading..."
    mkdir -p "${BOOT2DOCKER_ISO%/*}"
    curl -L -o "$BOOT2DOCKER_ISO" "https://github.com/steeve/boot2docker/releases/download/$LATEST_RELEASE/boot2docker.iso"
    log "Done"
}

log() {
    echo "[`date +"%Y-%m-%d %H:%M:%S"`] ${*}"
}

init() {

    if `$VBM showvminfo $VM_NAME > /dev/null 2>&1`; then
	    echo "$VM_NAME Virtual Box vm already exists"
	    exit 1
    fi

    VM_OSTYPE=Linux26_64
    VM_NIC=virtio
    unamestr=`uname`
    case $unamestr in
        Linux) VM_CPUS=`nproc`;;
        Darwin) VM_CPUS=`sysctl -n hw.physicalcpu`;;
        *) echo "$unamestr not yet supported - please raise an issue" ; exit 1
    esac

    log "Creating VM $VM_NAME"
    $VBM createvm --name $VM_NAME --register

    log "Setting VM settings"
    if ! $VBM modifyvm $VM_NAME \
        --ostype $VM_OSTYPE \
        --cpus $VM_CPUS \
        --memory $VM_MEM \
        --rtcuseutc on \
        --acpi on \
        --ioapic on \
        --hpet on \
        --hwvirtex on \
        --vtxvpid on \
        --vtxux on \
        --largepages on \
        --nestedpaging on \
        --firmware bios \
        --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled \
        --boot1 dvd; then
      echo "An error occured, upgrade VirtualBox or try to disable some options"
      delete
      exit 1
    fi

    log "Setting VM networking"
    $VBM modifyvm $VM_NAME \
        --nic1 nat \
        --nictype1 $VM_NIC \
        --cableconnected1 on
    if `$VBM showvminfo $VM_NAME | grep Rule | grep ssh > /dev/null`; then
	    $VBM modifyvm $VM_NAME \
        	--natpf1 delete "ssh"
    fi
    if `$VBM showvminfo $VM_NAME | grep Rule | grep docker > /dev/null`; then
	    $VBM modifyvm $VM_NAME \
        	--natpf1 delete "docker"
    fi
    $VBM modifyvm $VM_NAME \
        --nic2 hostonly \
        --hostonlyadapter2 vboxnet0 \
        --nictype2 $VM_NIC \
        --cableconnected2 on
    $VBM modifyvm $VM_NAME \
        --natpf1 "ssh,tcp,127.0.0.1,$SSH_HOST_PORT,,22" \
        --natpf1 "docker,tcp,127.0.0.1,$DOCKER_PORT,,4243"

    CFWPORTS=""
    for port in {49000..49900}
        do
            CFWPORTS="$CFWPORTS --natpf1 zfp$port,tcp,127.0.0.1,$port,,$port"
        done
    $VBM modifyvm $VM_NAME $CFWPORTS

    if [ ! -e $BOOT2DOCKER_ISO ]; then
        log "boot2docker.iso not found."
        download_latest
    fi

    log "Setting VM disks"
    if `$VBM showvminfo $VM_NAME | grep SATA > /dev/null`; then
        $VBM storagectl $VM_NAME --name "SATA" --remove
    fi

    if [ ! -e $VM_DISK ]; then
        log "Creating $VM_DISK_SIZE Meg hard drive..."
        # closemedium may complain when not needed
        mkdir -p "${VM_DISK%/*}"
        $VBM closemedium disk $VM_DISK > /dev/null 2>&1
        $VBM createhd --format VMDK --filename $VM_DISK --size $VM_DISK_SIZE
    fi

    $VBM storagectl $VM_NAME --name "SATA" --add sata --hostiocache on
    $VBM storageattach $VM_NAME --storagectl "SATA" --port 0 --device 0 --type dvddrive --medium $BOOT2DOCKER_ISO
    $VBM storageattach $VM_NAME --storagectl "SATA" --port 1 --device 0 --type hdd --medium $VM_DISK

    log "Done."
    log "You can now type boot2docker up and wait for the VM to start."
}

do_ssh() {
    is_installed || status
pkfile=`mktemp -t b2d`
umask 077
echo "-----BEGIN DSA PRIVATE KEY-----
MIIBvAIBAAKBgQCjs5tqiAMPBoRF9jUhytG1dVwDxVKH9U2tnmOCvIyZ7RVYrbw3
HqP1yGdhmua9DKpExJqTlIq/xosWqAeRZDHm9t0mFT1oW+fJytfF1LFeNujDdOIa
dE+Uh+gKqSQef0DXbdFRc7JdrG5FLriihb2r/PmrYNqAZhfnXfAZ6YZgcQIVAMlB
CZdlBCOclnLEpTWWOoDduYh5AoGBAJ3aG2EtKbJt65Jt49C3Q3v1vI/ETJ0409P6
XIjFk2p0IWOzIiLSPI4zMSkWl9bCwFcyhEN4Ngk+TSmIsamlheCpsM6tEmeHxhBn
BvV7a95IjTyiKBG+2kweMQapehpBvSnsH7/WpXNPxLhfZNq+q6vjZbPQvZ4lhqEA
7OilShIVAoGAAv8Px1V4tCJwPxnge+PTddeRNhD0Lwd6OpaKMo55u3qxpM+77M8q
84UpaNaX3dyKOHEVvoh4DvLEnAr9cPbZDG/pC39dsw8kOS/88sR+WGyu1hc05vyU
Ba8g4DSLDLFodM9KOOr33xpzISRYp0y6eyWCDlu+JE7+0kOBWMqqVicCFQCuBDEP
GcQgE6LgrKBC9bbzsgHq/w==
-----END DSA PRIVATE KEY-----
" > $pkfile
ssh -i $pkfile -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $SSH_HOST_PORT docker@localhost $1
rm $pkfile
}

start() {
    is_installed || status
    if ! is_running; then
        if is_paused; then
            log "Resuming $VM_NAME"
            $VBM controlvm $VM_NAME resume > /dev/null
            wait_vm
            log "Resumed."
        else
            log "Starting $VM_NAME..."
            $VBM startvm $VM_NAME --type headless > /dev/null &
            wait_vm
            log "Started."
        fi
    else
        log "$VM_NAME is already running."
    fi
}

wait_vm() {
    while ! echo "ping" | nc localhost $SSH_HOST_PORT > /dev/null; do
        sleep 1
    done
}

pause() {
    is_installed || status
    if is_running; then
        log "Pausing $VM_NAME..."
        $VBM controlvm $VM_NAME pause > /dev/null
    else
        log "$VM_NAME is not running."
    fi
}

stop() {
    is_installed || status
    if is_running; then
        log "Shutting down $VM_NAME..."
        $VBM controlvm $VM_NAME acpipowerbutton > /dev/null
        while is_running; do
            sleep 1
        done
    else
        log "$VM_NAME is not running."
    fi
}

restart() {
    is_installed || status
    if is_running; then
        stop && sleep 1 && start
    else
        start
    fi
}

info() {
    if is_installed; then
        $VBM showvminfo $VM_NAME
    else
        echo "$VM_NAME does not exist."
    fi
}

is_installed() {
    $VBM list vms | grep "$VM_NAME" > /dev/null
}

is_running() {
    info | grep "State:\s\+running" > /dev/null
}

is_paused() {
    info | grep "State:\s\+paused" > /dev/null
}

is_stopped() {
    info | grep "State:\s\+powered off" > /dev/null
}

is_aborted() {
    info | grep "State:\s\+aborted" > /dev/null
}

status() {
    if is_running; then
        log "$VM_NAME is running."
        exit 0
    elif is_paused; then
        log "$VM_NAME is suspended."
        exit 1
    elif is_stopped; then
        log "$VM_NAME is stopped."
        exit 1
    else
        log "$VM_NAME does not exist."
        exit 1
    fi
}

delete() {
    if [ ! is_stopped ] || [ ! is_aborted ]; then
        log "$VM_NAME needs to be stopped to delete it."
        exit 1
    fi
    $VBM unregistervm --delete $VM_NAME
}

build() {
    if ! is_running; then
        log "$VM_NAME needs to be running to build a new ISO."
        exit 1
    fi
    if [ -n "$1" ]; then
        repo="$1"
    elif [ ! -f "./rootfs/Dockerfile" ]; then
        repo="git@github.com:steeve/boot2docker.git"
    fi
    if [ -n "$repo" ]; then
        log "Create TEMPDIR."
        builddir=$(mktemp -d -t b2d)
        pushd $builddir

        log "Download $repo."

        git clone $repo .

        # curl -o master.zip $repo
        # if [ ! -f "./master.zip" ]; then
        #     log "Download failed!"
        #     exit
        # fi   
        # unzip master.zip
        if [ ! -f "./rootfs/Dockerfile" ]; then
            log "No Repository to build!"
            exit
        fi  
    else
        log "Use local repository."
    fi

    log "Start build"
    docker pull steeve/boot2docker-base
    docker build -rm -t boot2docker rootfs/
    docker rm build-boot2docker  > /dev/null 2>&1

    docker run -privileged -name build-boot2docker boot2docker
    if [ -n "$repo" ]; then
        popd
        chmod -R 777 $builddir
        rm -R $builddir
    fi

    echo "wait for container to finish"
    docker wait build-boot2docker
 
    docker cp build-boot2docker:/boot2docker.iso .
    # ToDo: replace existing ISO
    echo "path to old ISO:"
    $VBM showvminfo $VM_NAME | grep boot2docker.iso
}

docker_cmd() {
    echo "CMD: $@"
    DCMD=$@
    if [[ $DCMD =~ [-]name[[:space:]]([a-zA-Z0-9_-]+) ]]; then
        CNAME=${BASH_REMATCH[1]}
        # echo "name: $CNAME"
    fi
    if [[ -n "$CNAME" ]] && [[ $DCMD =~ -p[[:space:]]([a-zA-Z0-9_\\-\\.]*):*([0-9]*):*([0-9]*)(/udp){0,1} ]]; then
        # echo $BASH_REMATCH      
        # echo ${BASH_REMATCH[1]} 
        # echo ${BASH_REMATCH[2]} 
        # echo ${BASH_REMATCH[3]} 
        # echo ${BASH_REMATCH[4]}
        PP0=$BASH_REMATCH
        PP1=${BASH_REMATCH[1]}
        PP2=${BASH_REMATCH[2]}
        PP3=${BASH_REMATCH[3]}
        PP4=${BASH_REMATCH[4]}
        if [[ $PP1 =~ [a-zA-Z0-9](-*[a-zA-Z0-9]+)*(\.[a-zA-Z0-9](-*[a-zA-Z0-9]+)*)+ ]]; then
            PB_HOST_IF=$PP1
            if [ "" == "$PP3" ]; then
                PB_CPORT=$PP2
            else
                PB_CPORT=$PP3
                PB_HPORT=$PP2
            fi
        else
            # echo "no IP"
            if [ "" == "$PP2" ]; then
                PB_CPORT=$PP1
            else
                PB_CPORT=$PP2
                PB_HPORT=$PP1
            fi
        fi
        PB_OPTION="-p 0.0.0.0::$PB_CPORT"
        if [ "" == "$PP4" ]; then
            PB_TYP=tcp
        else
            PB_TYP=udp
        fi
        # echo "$PB_HOST_IF:$PB_HPORT:$PB_CPORT"
        # echo "$PB_OPTION"
        DCMD="${DCMD/$PP0/$PB_OPTION}"
        echo "docker $DCMD"

        docker $DCMD
        # echo "docker port $CNAME $PB_CPORT"
        PBDYN=$(docker port $CNAME $PB_CPORT)
        # echo $PBDYN
        if [[ $PBDYN =~ ([a-zA-Z0-9_\\-\\.]*):*([0-9]*) ]]; then
            PB_VM_IF=${BASH_REMATCH[1]}
            # PB_VM_IF=""
            PB_DPORT=${BASH_REMATCH[2]}
            if [ "" == "$PB_HOST_IF" ]; then
                PB_HOST_IF="127.0.0.1"
            fi
            if [ "" == "$PB_HPORT" ]; then
                PB_HPORT=$PB_DPORT
            fi
            CFWPORTS=""
            CFWPORTS="$CFWPORTS natpf1 zfp$PB_HPORT,$PB_TYP,$PB_HOST_IF,$PB_HPORT,$PB_VM_IF,$PB_DPORT"
            #echo $CFWPORTS
            echo "$VBM controlvm $VM_NAME natpf1 delete zfp$PB_HPORT"
            echo "$VBM controlvm $VM_NAME $CFWPORTS"
            $VBM controlvm $VM_NAME setlinkstate1 off
            $VBM controlvm $VM_NAME natpf1 delete zfp$PB_HPORT  > /dev/null 2>&1
            $VBM controlvm $VM_NAME $CFWPORTS
            $VBM controlvm $VM_NAME setlinkstate1 on
        fi
    else
        echo "missed"
        docker $1
    fi
}

case $1 in
    init | setup) init;;
    start | up) start;;
    pause | suspend) pause;;
    stop | halt | down) stop;;
    restart) restart;;
    status) status;;
    info) info;;
    delete) delete;;
    ssh) shift; do_ssh "$@";;
    download) download_latest;;
    build) shift; build $1;;
    cmd) shift; docker_cmd "$@";;
    *) echo "Usage $0 {init|start|up|pause|stop|restart|status|info|delete|ssh|download|build|cmd}"; exit 1
esac
