#!/bin/sh

# Configure sshd and acknoledge for persistence in /var/lib/docker of the keys/config
# More /usr/local/etc/ssh to /var/lib/docker/ssh if it doesn't exist
if [ ! -d /var/lib/docker/vm/ssh ]; then
    mkdir -p /var/lib/docker/vm
    mv /usr/local/etc/ssh /var/lib/docker/vm/
else # if it exists, remove the ramdisk's ssh config, so that the hard drive's is properly linked
    rm -rf /usr/local/etc/ssh
fi
ln -s /var/lib/docker/vm/ssh /usr/local/etc/ssh

if [ ! -f /usr/local/etc/ssh/ssh_config ]; then
    mv /usr/local/etc/ssh/ssh_config.example /usr/local/etc/ssh/ssh_config
fi
if [ ! -f /usr/local/etc/ssh/sshd_config ]; then
    mv /usr/local/etc/ssh/sshd_config.example /usr/local/etc/ssh/sshd_config
    cat <<EOT >> /usr/local/etc/ssh/sshd_config
Match User docker
    AuthorizedKeysFile        /home/docker/.ssh/authorized_keys
EOT
	mkdir -p /home/docker/.ssh/
	mv /usr/local/etc/ssh/docker/authorized_keys /home/docker/.ssh/authorized_keys
	chown -R docker:docker /usr/local/etc/ssh/docker
	chmod 700 /home/docker/.ssh
	chmod 600 /home/docker/.ssh/authorized_keys
fi

/usr/local/etc/init.d/openssh start
